
# Levantaremos dos servicios: MySQL 8 y phpMyAdmin

version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: 'AED-MySQL-practica1JDBC'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: practicaJDBC
      MYSQL_USER: usuarioexterno
      MYSQL_PASSWORD: Toor.toor1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: 'AED_phpMyAdmin-practica1JDBC'
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
    